### ISSUE TITLE
Initial value incorrect when 'update_input_field_name' is setted

### ISSUE THREAD

**Issue by debaser** [auxiliary/rater#4]
The bond field always gets initial value 5. 

This wrong value is set in line 173:
this.value = this.toValue(selected_width \* $(base_layer).textWidth());

**Comment by auxiliary** [comment]
@debaser The `update_input_field_name` is used to set a text field that gets updated with the value of the rate once it's changed. If you want to set an initial value for the rater, you have to use the `initial_value` option. Also, line 173 uses `selected_width` and that's calculated based on the initial value at line 121. Please let me know if I misunderstood and there's actually a bug there.

**Comment by debaser** [comment]
Hi!,

Please, test this simple code, and notice that the input value will change
to 5. Thank you

<!DOCTYPE html>
<html >
  <head>
    <meta charset="UTF-8">
    <title>Rater</title>
     <script src='
http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

<script src='
https://raw.githubusercontent.com/auxiliary/rater/master/rater.js'></script>
  </head>
  <body>
    <input type="text" id="rate" value="2" /> 
<p id="rating"></p>
<script>
$(document).ready(function() {
 $("#rating").rate({
   symbols: {
     custom: {
       base: '\u2605',
       hover: '\u2605',
       selected: '\u2605',
     },
   },
   selected_symbol_type: 'custom',
   max_value: 5,
   step_size: 1,
   initial_value: $("#rate").val() || 0,
   cursor: 'pointer',
   update_input_field_name: $("#rate")
 });
});
</script>

  </body>
</html>

**Comment by debaser** [comment]
Here is a simplier code, better to understand, with the main info isolated:

```
<input type="text" id="rate" value="2" /> <!-- After the script, this value will change to 5 -->
<p id="rating"></p>

<script>
$(document).ready(function() {
  $("#rating").rate({
    max_value: 5,
    step_size: 1,
    initial_value: 2,
    cursor: 'pointer',
    update_input_field_name: $("#rate")
  });
});
</script>
```

**Comment by auxiliary** [comment]
hmm, I see. it should be fixed now. I'll close this issue. If the problem persists please reopen it. 
BTW, in your sample code, you might want to change the base character to `base: '\u2606'` to be an empty star.
