### ISSUE TITLE
Size?

### ISSUE THREAD

**Issue by kokujin** [auxiliary/rater#5]
Is it possible to modify the size of the stars? If yes, how? Thanks

**Comment by auxiliary** [comment]
If you're using the unicode mode or the FontAwesome mode then yes. Simply change the font size for the rater element. For example in the index.html demo page, you can change the size of the hearts by setting font-size for `.rate2`.

**Comment by kokujin** [comment]
Are you sure? Font size settings don't have any effect for me

```
<div class="rating" data-rate-value=6></div>

  // Options
  var options = {
    'max_value': 5,
    'step_size': 0.5,
    'initial_value': 0,
    'selected_symbol_type': 'utf8_star', // Must be a key from symbols
    cursor: 'default',
    readonly: false,
    'change_once': false, // Determines if the rating can only be set once
    'ajax_method': 'POST',
    url: 'http://localhost/test.php',
    'additional_data': {} // Additional data to send to the server
  };

  $('.rating').rate(options);
```

Any ideas why this does not work as expected?

**Comment by auxiliary** [comment]
This works for me with your example:

```
.rating
{
    font-size: 70px; 
}
```

What browser and version are you using?

**Comment by kokujin** [comment]
Thanks @auxiliary . I could get it to work
